// mapQ is the Google Maps search query string for each location.
// Links are generated as: https://www.google.com/maps/search/?api=1&query=...

export const LOCATIONS = [
  // UK & Ireland
  {
    id: "glasgow",
    name: "Nelson Mandela Place",
    city: "Glasgow",
    country: "Scotland, UK",
    flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
    continent: "Europe",
    mapQ: "Homeless Jesus Nelson Mandela Place Glasgow",
  },
  {
    id: "manchester",
    name: "St Ann's Church",
    city: "Manchester",
    country: "England, UK",
    flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    continent: "Europe",
    mapQ: "St Ann's Church Manchester",
  },
  {
    id: "liverpool",
    name: "Church of Our Lady and Saint Nicholas",
    city: "Liverpool",
    country: "England, UK",
    flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    continent: "Europe",
    mapQ: "Church of Our Lady and Saint Nicholas Liverpool",
  },
  {
    id: "london",
    name: "London (exact location TBC)",
    city: "London",
    country: "England, UK",
    flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    continent: "Europe",
    mapQ: "Homeless Jesus statue London",
  },
  {
    id: "belfast",
    name: "Belfast (exact location TBC)",
    city: "Belfast",
    country: "Northern Ireland, UK",
    flag: "🇬🇧",
    continent: "Europe",
    mapQ: "Homeless Jesus statue Belfast",
  },
  {
    id: "dublin",
    name: "Christ Church Cathedral",
    city: "Dublin",
    country: "Ireland",
    flag: "🇮🇪",
    continent: "Europe",
    mapQ: "Christ Church Cathedral Dublin Ireland",
  },
  {
    id: "cork",
    name: "St Fin Barre's Cathedral",
    city: "Cork",
    country: "Ireland",
    flag: "🇮🇪",
    continent: "Europe",
    mapQ: "St Fin Barre Cathedral Cork Ireland",
  },

  // Continental Europe
  {
    id: "vatican",
    name: "Papal Charities Building",
    city: "Vatican City",
    country: "Vatican City",
    flag: "🇻🇦",
    continent: "Europe",
    mapQ: "Homeless Jesus Vatican City Papal Charities Building",
  },
  {
    id: "rome",
    name: "San Marcello al Corso Basilica",
    city: "Rome",
    country: "Italy",
    flag: "🇮🇹",
    continent: "Europe",
    mapQ: "San Marcello al Corso Basilica Rome Italy",
  },
  {
    id: "bruges",
    name: "Bruges (exact location TBC)",
    city: "Bruges",
    country: "Belgium",
    flag: "🇧🇪",
    continent: "Europe",
    mapQ: "Homeless Jesus statue Bruges Belgium",
  },
  {
    id: "santiago",
    name: "Pilgrim Reception Office, Cathedral",
    city: "Santiago de Compostela",
    country: "Spain",
    flag: "🇪🇸",
    continent: "Europe",
    mapQ: "Pilgrim Reception Office Cathedral Santiago de Compostela Spain",
  },
  {
    id: "madrid",
    name: "Madrid (exact location TBC)",
    city: "Madrid",
    country: "Spain",
    flag: "🇪🇸",
    continent: "Europe",
    mapQ: "Homeless Jesus statue Madrid Spain",
  },
  {
    id: "fatima",
    name: "Fatima Shrine",
    city: "Fatima",
    country: "Portugal",
    flag: "🇵🇹",
    continent: "Europe",
    mapQ: "Sanctuary of Fatima Portugal",
  },
  {
    id: "poland",
    name: "Poland (exact location TBC)",
    city: "Poland",
    country: "Poland",
    flag: "🇵🇱",
    continent: "Europe",
    mapQ: "Homeless Jesus statue Poland",
  },

  // Canada
  {
    id: "toronto",
    name: "Regis College, University of Toronto",
    city: "Toronto, ON",
    country: "Canada",
    flag: "🇨🇦",
    continent: "North America",
    mapQ: "Regis College 100 Wellesley Street West Toronto",
  },
  {
    id: "hamilton",
    name: "Hamilton (exact location TBC)",
    city: "Hamilton, ON",
    country: "Canada",
    flag: "🇨🇦",
    continent: "North America",
    mapQ: "Homeless Jesus statue Hamilton Ontario Canada",
  },
  {
    id: "ottawa",
    name: "Ottawa (exact location TBC)",
    city: "Ottawa, ON",
    country: "Canada",
    flag: "🇨🇦",
    continent: "North America",
    mapQ: "Homeless Jesus statue Ottawa Canada",
  },
  {
    id: "montreal",
    name: "St. James United Church",
    city: "Montreal, QC",
    country: "Canada",
    flag: "🇨🇦",
    continent: "North America",
    mapQ: "St James United Church Montreal Quebec",
  },
  {
    id: "vancouver",
    name: "Holy Rosary Cathedral",
    city: "Vancouver, BC",
    country: "Canada",
    flag: "🇨🇦",
    continent: "North America",
    mapQ: "Holy Rosary Cathedral Vancouver British Columbia",
  },

  // USA
  {
    id: "davidson",
    name: "St. Alban's Episcopal Church",
    city: "Davidson, NC",
    country: "USA",
    flag: "🇺🇸",
    continent: "North America",
    mapQ: "St Alban's Episcopal Church Davidson North Carolina",
  },
  {
    id: "washington",
    name: "Basilica of the National Shrine",
    city: "Washington D.C.",
    country: "USA",
    flag: "🇺🇸",
    continent: "North America",
    mapQ: "Basilica National Shrine Immaculate Conception Washington DC",
  },
  {
    id: "charleston",
    name: "St. Mark's United Methodist Church",
    city: "Charleston, WV",
    country: "USA",
    flag: "🇺🇸",
    continent: "North America",
    mapQ: "St Mark's United Methodist Church Charleston West Virginia",
  },
  {
    id: "buffalo",
    name: "St. Paul's Cathedral",
    city: "Buffalo, NY",
    country: "USA",
    flag: "🇺🇸",
    continent: "North America",
    mapQ: "St Paul's Cathedral Buffalo New York",
  },
  {
    id: "newyork",
    name: "Cathedral of St. John the Divine",
    city: "New York, NY",
    country: "USA",
    flag: "🇺🇸",
    continent: "North America",
    mapQ: "Cathedral of St John the Divine New York City",
  },
  {
    id: "detroit",
    name: "Saints Peter and Paul Jesuit Church",
    city: "Detroit, MI",
    country: "USA",
    flag: "🇺🇸",
    continent: "North America",
    mapQ: "Saints Peter and Paul Jesuit Church Detroit Michigan",
  },
  {
    id: "knoxville",
    name: "Knoxville (exact location TBC)",
    city: "Knoxville, TN",
    country: "USA",
    flag: "🇺🇸",
    continent: "North America",
    mapQ: "Homeless Jesus statue Knoxville Tennessee",
  },
  {
    id: "chicago",
    name: "Catholic Charities HQ, River North",
    city: "Chicago, IL",
    country: "USA",
    flag: "🇺🇸",
    continent: "North America",
    mapQ: "Catholic Charities Archdiocese Chicago 721 N LaSalle",
  },
  {
    id: "austin",
    name: "Central Presbyterian Church",
    city: "Austin, TX",
    country: "USA",
    flag: "🇺🇸",
    continent: "North America",
    mapQ: "Central Presbyterian Church Austin Texas",
  },
  {
    id: "okc",
    name: "Catholic Charities Oklahoma City",
    city: "Oklahoma City, OK",
    country: "USA",
    flag: "🇺🇸",
    continent: "North America",
    mapQ: "Catholic Charities Archdiocese Oklahoma City",
  },
  {
    id: "denver",
    name: "Father Woody's Haven of Hope",
    city: "Denver, CO",
    country: "USA",
    flag: "🇺🇸",
    continent: "North America",
    mapQ: "Father Woody's Haven of Hope Denver Colorado",
  },
  {
    id: "valparaiso",
    name: "Valparaiso University",
    city: "Valparaiso, IN",
    country: "USA",
    flag: "🇺🇸",
    continent: "North America",
    mapQ: "Valparaiso University Indiana",
  },
  {
    id: "grandhaven",
    name: "Grand Haven (exact location TBC)",
    city: "Grand Haven, MI",
    country: "USA",
    flag: "🇺🇸",
    continent: "North America",
    mapQ: "Homeless Jesus statue Grand Haven Michigan",
  },
  {
    id: "phoenix",
    name: "Phoenix (exact location TBC)",
    city: "Phoenix, AZ",
    country: "USA",
    flag: "🇺🇸",
    continent: "North America",
    mapQ: "Homeless Jesus statue Phoenix Arizona",
  },
  {
    id: "albuquerque",
    name: "Albuquerque (exact location TBC)",
    city: "Albuquerque, NM",
    country: "USA",
    flag: "🇺🇸",
    continent: "North America",
    mapQ: "Homeless Jesus statue Albuquerque New Mexico",
  },
  {
    id: "minneapolis",
    name: "The Basilica of Saint Mary",
    city: "Minneapolis, MN",
    country: "USA",
    flag: "🇺🇸",
    continent: "North America",
    mapQ: "Basilica of Saint Mary Minneapolis Minnesota",
  },
  {
    id: "fargo",
    name: "Fargo (exact location TBC)",
    city: "Fargo, ND",
    country: "USA",
    flag: "🇺🇸",
    continent: "North America",
    mapQ: "Homeless Jesus statue Fargo North Dakota",
  },
  {
    id: "elyria",
    name: "First Congregational Church",
    city: "Elyria, OH",
    country: "USA",
    flag: "🇺🇸",
    continent: "North America",
    mapQ: "First Congregational Church Elyria Ohio",
  },
  {
    id: "bayvillage",
    name: "Bay Village (exact location TBC)",
    city: "Bay Village, OH",
    country: "USA",
    flag: "🇺🇸",
    continent: "North America",
    mapQ: "Homeless Jesus statue Bay Village Ohio",
  },
  {
    id: "cleveland",
    name: "St. Malachi Church",
    city: "Cleveland, OH",
    country: "USA",
    flag: "🇺🇸",
    continent: "North America",
    mapQ: "St Malachi Church Cleveland Ohio",
  },

  // South America
  {
    id: "buenosaires",
    name: "Metropolitan Cathedral",
    city: "Buenos Aires",
    country: "Argentina",
    flag: "🇦🇷",
    continent: "South America",
    mapQ: "Metropolitan Cathedral Buenos Aires Argentina",
  },

  // Africa
  {
    id: "johannesburg",
    name: "Johannesburg (exact location TBC)",
    city: "Johannesburg",
    country: "South Africa",
    flag: "🇿🇦",
    continent: "Africa",
    mapQ: "Homeless Jesus statue Johannesburg South Africa",
  },

  // Middle East
  {
    id: "capernaum",
    name: "Church of St. Peter",
    city: "Capernaum",
    country: "Israel",
    flag: "🇮🇱",
    continent: "Middle East",
    mapQ: "Church of St Peter Capernaum Israel Sea of Galilee",
  },

  // Asia
  {
    id: "singapore",
    name: "Singapore (exact location TBC)",
    city: "Singapore",
    country: "Singapore",
    flag: "🇸🇬",
    continent: "Asia",
    mapQ: "Homeless Jesus statue Singapore",
  },

  // Oceania
  {
    id: "townsville",
    name: "Sacred Heart Cathedral",
    city: "Townsville, QLD",
    country: "Australia",
    flag: "🇦🇺",
    continent: "Oceania",
    mapQ: "Sacred Heart Cathedral Townsville Queensland Australia",
  },
  {
    id: "melbourne",
    name: "Newman College, University of Melbourne",
    city: "Melbourne, VIC",
    country: "Australia",
    flag: "🇦🇺",
    continent: "Oceania",
    mapQ: "Newman College University of Melbourne",
  },
  {
    id: "sydney",
    name: "St James Anglican Church",
    city: "Sydney, NSW",
    country: "Australia",
    flag: "🇦🇺",
    continent: "Oceania",
    mapQ: "St James Anglican Church King Street Sydney",
  },
];

export const CONTINENTS = [
  "All",
  "Europe",
  "North America",
  "South America",
  "Oceania",
  "Africa",
  "Middle East",
  "Asia",
];

export const TOTAL_WORLDWIDE = 100;

export function mapsUrl(loc) {
  return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(loc.mapQ)}`;
}
